import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

// Central path variables
const CYPRESS_FIXTURES_PATH = 'cypress/fixtures';
const CYPRESS_TYPES_PATH = 'cypress/types/fixtures.d.ts';

const fixturesDir: string = path.resolve(process.cwd(), CYPRESS_FIXTURES_PATH);
const outputFile: string = path.resolve(process.cwd(), CYPRESS_TYPES_PATH);

function getFixtureFiles(dir: string, baseDir: string = dir): string[] {
  let results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const list: string[] = fs.readdirSync(dir);
  list.forEach((file: string) => {
    const filePath: string = path.join(dir, file);
    const stat: fs.Stats = fs.statSync(filePath);

    if (stat && stat.isDirectory()) {
      results = results.concat(getFixtureFiles(filePath, baseDir));
    } else {
      const relPath: string = path.relative(baseDir, filePath).replace(/\\/g, '/');
      results.push(`  | '${relPath}'`);
    }
  });

  return results;
}

function autofixGeneratedFile(filePath: string): void {
  try {
    execSync(`npx eslint --fix "${filePath}"`, { stdio: 'ignore' });
  } catch {
    // Ignore if ESLint is missing or throws warnings
  }

  try {
    execSync(`npx prettier --write "${filePath}"`, { stdio: 'ignore' });
  } catch {
    // Ignore if Prettier is missing
  }
}

function generateTypes(): void {
  const files: string[] = getFixtureFiles(fixturesDir);
  const fixtureTypes: string = files.length > 0 ? files.join('\n') : '  | string';

  const content: string = `
// Auto-generated by scripts/generate-fixture-types.ts. Do not edit directly.

declare namespace Cypress {
  type FixtureName = ${fixtureTypes};

  /**
   * Typed StaticResponse leveraging Cypress's native GenericStaticResponse<Fixture, Body>
   */
  type TypedStaticResponse<Body = unknown> = GenericStaticResponse<FixtureName, Body>;

  interface Chainable {
    /**
     * Get a data fixture file with type safety.
     */
    fixture<T = unknown>(
      filePath: FixtureName,
      options?: Partial<Timeoutable>
    ): Chainable<T>;

    fixture<T = unknown>(
      filePath: FixtureName,
      encoding: Encodings,
      options?: Partial<Timeoutable>
    ): Chainable<T>;
  }
}
`;

  const outputDir: string = path.dirname(outputFile);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputFile, content);
  autofixGeneratedFile(outputFile);

  console.info(`[${new Date().toLocaleTimeString()}] Updated and formatted ${CYPRESS_TYPES_PATH}`);
}

generateTypes();

const isWatchMode = process.argv.includes('--watch') || process.argv.includes('-w');

if (isWatchMode) {
  console.info(`Watching ${CYPRESS_FIXTURES_PATH} directory for updates...`);

  let debounceTimer: NodeJS.Timeout | null = null;

  if (fs.existsSync(fixturesDir)) {
    fs.watch(fixturesDir, { recursive: true }, () => {
      if (debounceTimer) clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        generateTypes();
      }, 100);
    });
  }
}
