// Auto-generated by scripts/generate-fixture-types.ts. Do not edit directly.

declare namespace Cypress {
  type FixtureName = 'post-recommendations.json';

  /**
   * Typed StaticResponse leveraging Cypress's native GenericStaticResponse<Fixture, Body>
   */
  type TypedStaticResponse<Body = unknown> = GenericStaticResponse<FixtureName, Body>;

  interface Chainable {
    /**
     * Get a data fixture file with type safety.
     */
    fixture<T = unknown>(filePath: FixtureName, options?: Partial<Timeoutable>): Chainable<T>;

    fixture<T = unknown>(
      filePath: FixtureName,
      encoding: Encodings,
      options?: Partial<Timeoutable>,
    ): Chainable<T>;
  }
}
