name: CI-Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install packages
        run: npm i

      - name: App production build
        run: npm run build:prod

      - name: Run linter for ESlint
        run: npm run lint:code

      - name: Run linter for TS
        run: npm run lint:ts

      - name: Run linter for SCSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run screenshot tests
        run: npm run test:sshot:ci
